In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

file_path = "NarrateIQ_ML_Dataset.xlsx"
df = pd.read_excel(file_path)
df.head()

,Student_ID,Age_Group,Disability_Type,Severity_Level,State,School_Type,Language,Teacher_Experience,Input_Mode,Content_Format,...,Offline_Mode_Used,Device_Type,Parental_Involvement,Engagement_Score,Attention_Span_Min,Completion_Rate_Pct,Comprehension_Score,Teacher_Satisfaction,Improvement_Score_Pct,Learning_Outcome
0,STU1000,11-13,Autism,Mild,UP,Special School,Hindi,5+ Years,Video,Animated Video,...,0,Laptop,3,63.4,6.9,86.4,42.2,4.4,46.6,Average
1,STU1001,5-7,Multiple,Mild,UP,NGO,Telugu,3-5 Years,Video,Text+Audio,...,1,Phone,2,79.0,21.8,61.9,68.5,3.9,30.2,Average
2,STU1002,5-7,ADHD,Mild,Karnataka,Government,Hindi,3-5 Years,Audio,Animated Video,...,0,Tablet,2,63.4,3.7,66.5,61.4,4.1,32.6,Average
3,STU1003,8-10,ADHD,Mild,West Bengal,Government,English,1-3 Years,Text,ISL Avatar,...,0,Phone,4,79.6,6.0,69.0,86.6,4.4,72.6,Good
4,STU1004,8-10,Dyslexia,Mild,Gujarat,Government,Kannada,1-3 Years,Video,Animated Video,...,1,Phone,4,82.7,13.8,100.0,83.4,3.1,42.6,Good

In [2]:
X = df[["Session_Duration_Min", "Months_on_Platform"]]
y=df["Improvement_Score_Pct"]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [4]:
X_test

     Session_Duration_Min  Months_on_Platform
82                      6                   8
473                    32                  14
49                     32                   1
231                    17                   4
590                    21                  17
..                    ...                 ...
65                     24                   1
198                    38                  23
43                     32                  11
404                    25                   9
39                      5                   7

[180 rows x 2 columns]

In [5]:
y_test

82     58.0
473    45.0
49     27.1
231    42.1
590    49.5
       ...
65     27.8
198    35.0
43     43.3
404    12.6
39     53.5
Name: Improvement_Score_Pct, Length: 180, dtype: float64

In [6]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [7]:
clf.predict(X_test)

array([35.08346735, 40.03792131, 28.3560237 , 31.30407186, 42.91870929,
       46.27772874, 40.93652881, 35.54488377, 43.76687168, 28.52417412,
       49.00718135, 42.17143716, 44.6318491 , 36.74616203, 43.78368672,
       47.04181591, 35.7971094 , 30.03553342, 48.90629109, 41.25601461,
       36.47712136, 41.10467923, 42.91870929, 37.34209878, 49.04081143,
       30.53998468, 30.25412897, 43.64916638, 49.4275574 , 31.47222228,
       42.98596946, 31.01821614, 35.54488377, 30.1868688 , 46.34498891,
       36.67890186, 37.52706424, 48.10857384, 36.54438153, 41.6669859 ,
       43.69961151, 31.40496211, 43.71642655, 43.98546722, 35.84755452,
       29.6918223 , 41.37371991, 41.88558145, 35.49443864, 33.23580721,
       44.59821902, 40.90289873, 30.43909443, 34.73035147, 33.21899217,
       30.42227939, 49.29303706, 35.69621914, 36.25852581, 43.44738588,
       46.27772874, 44.54777389, 39.52605976, 35.03302222, 36.76297707,
       44.54777389, 45.79949728, 42.93552434, 43.53146109, 29.35552146,
       30.27094401, 37.6279545 , 39.54287481, 32.98358158, 39.49242968,
       29.67500726, 36.27534085, 36.86386732, 34.96576206, 31.10229135,
       33.05084175, 32.98358158, 40.29014694, 35.10028239, 48.90629109,
       29.55730196, 47.95723846, 29.10329583, 46.64765966, 42.53196333,
       47.49582204, 41.63335582, 29.13692591, 46.19365353, 47.26041146,
       29.62456213, 43.9350221 , 43.58190621, 35.41036343, 43.9350221 ,
       28.81002983, 34.51175592, 41.2896447 , 40.25651685, 35.10028239,
       43.56509117, 45.63134686, 41.71743103, 30.52316964, 39.86977089,
       30.28775905, 38.35841158, 29.12011087, 28.28876353, 32.30356962,
       41.81832128, 35.76347931, 41.2896447 , 42.08736195, 40.88608369,
       32.74817099, 35.98207486, 36.25852581, 41.25601461, 40.73474831,
       45.86675745, 33.151732  , 39.17294388, 48.32716938, 45.73223711,
       30.86688076, 44.66547918, 29.12011087, 30.01871838, 47.64715742,
       43.0027845 , 44.98496498, 41.15512436, 33.05084175, 32.06815903,
       31.38814707, 44.91770481, 28.38965378, 43.18774997, 48.83903093,
       38.95434834, 49.3098521 , 39.47561464, 43.75005663, 42.75055887,
       49.25940698, 43.76687168, 49.44437244, 32.8322462 , 35.84755452,
       34.05033951, 42.17143716, 36.61164169, 29.25463121, 48.24309417,
       39.20657397, 36.84705228, 29.06966575, 48.95673622, 33.79811388,
       46.73173487, 32.20267936, 35.10028239, 34.1680448 , 37.44298903,
       39.55968985, 34.4613108 , 44.48051372, 47.42856188, 30.95095597,
       28.49054404, 48.02449863, 37.34209878, 35.66258906, 34.20167488])

In [8]:
clf.score(X_test, y_test)

0.1811442199230211

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=10)
X_test

     Session_Duration_Min  Months_on_Platform
69                     10                  20
27                     42                  21
488                    14                   9
540                    22                   4
285                    14                   3
..                    ...                 ...
582                     6                   5
402                    16                  24
126                    39                  16
434                    12                  13
576                     8                  15

[180 rows x 2 columns]